version: '3.8'

services:
 mongo-products:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_product_data:/data/db
  healthcheck:
    test: ["CMD", "echo", "MongoDB is running"]
    interval: 10s
    timeout: 5s
    retries: 5

 mysql-order:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_order_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
   MYSQL_DATABASE: orderdb
  healthcheck:
    test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1" ]
    interval: 10s
    timeout: 5s
    retries: 5

 mysql-inventory:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_inventory_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
   MYSQL_DATABASE: inventorydb
  healthcheck:
    test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1" ]
    interval: 10s
    timeout: 5s
    retries: 5

 mysql-user:
  image: mysql:latest
  ports:
    - 3308:3306
  volumes:
    - mysql_user_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
   MYSQL_DATABASE: userdb
  healthcheck:
    test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1" ]
    interval: 10s
    timeout: 5s
    retries: 5

 product-service:
  image: matthivr1987/product-service
  depends_on:
    mongo-products:
      condition: service_healthy
  ports:
    - 8080:8080
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-products

 inventory-service:
  image: matthivr1987/inventory-service
  depends_on:
    mysql-inventory:
      condition: service_healthy
    order-service:
      condition: service_started
  ports:
    - 8082:8082
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-inventory
   MYSQL_DB_PORT: 3306

 order-service:
  image: matthivr1987/order-service
  depends_on:
    product-service:
      condition: service_started
    mysql-order:
      condition: service_healthy
  ports:
    - 8081:8081
  environment:
   PRODUCT_SERVICE_BASEURL: product-service:8080
   INVENTORY_SERVICE_BASEURL: inventory-service:8082
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-order
   MYSQL_DB_PORT: 3306

 user-service:
  image: matthivr1987/user-service
  depends_on:
    product-service:
      condition: service_started
    mysql-user:
      condition: service_healthy
  ports:
    - 8083:8083
  environment:
   PRODUCT_SERVICE_BASEURL: product-service:8080
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-user
   MYSQL_DB_PORT: 3306

volumes:
 mongodb_product_data:
 mysql_inventory_data:
 mysql_order_data:
 mysql_user_data: