services:
 mongo-products:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_product_data:/data/db

 mysql-order:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_order_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123

 mysql-inventory:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_inventory_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123

 mysql-user:
  image: mysql:latest
  ports:
    - 3308:3306
  volumes:
    - mysql_user_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123

 product-service:
  build: ./product-service
  depends_on:
    - mongo-products
  ports:
    - 8080:8080
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-products

 inventory-service:
  build: ./inventory-service
  depends_on:
    - mysql-inventory
  ports:
    - 8082:8082
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-inventory
   MYSQL_DB_PORT: 3307

 order-service:
  build: ./order-service
  depends_on:
    - product-service
    - inventory-service
    - mysql-order
  ports:
    - 8081:8081
  environment:
   PRODUCT_SERVICE_BASEURL: product-service:8080
   INVENTORY_SERVICE_BASEURL: inventory-service:8082
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-order
   MYSQL_DB_PORT: 3306

 user-service:
  build: ./user-service
  depends_on:
    - product-service
    - mysql-user
  ports:
    - 8083:8083
  environment:
   PRODUCT_SERVICE_BASEURL: product-service:8080
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-user
   MYSQL_DB_PORT: 3308

volumes:
 mongodb_product_data:
 mysql_inventory_data:
 mysql_order_data:
 mysql_user_data: