server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/users
            - Method=POST
          filters:
            - SetPath=/api/user
        - id: user-service-email
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/users
            - Method=GET
          filters:
            - SetPath=/api/user
        - id: user-service-all
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/users/all
            - Method=GET
          filters:
            - SetPath=/api/user/all
        - id: user-service-id
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/users/{id}
            - Method=GET
          filters:
            - SetPath=/api/user/{id}
        - id: user-service-products
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/users/{id}/products
            - Method=GET
          filters:
            - SetPath=/api/user/{id}/products
        - id: user-service-update
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/users/{id}
            - Method=PUT
          filters:
            - SetPath=/api/user/{id}
        - id: user-service-addproduct
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/users/{id}/products/{skuCode}
            - Method=POST
          filters:
            - SetPath=/api/user/{id}/products/{skuCode}
        - id: product-service
          uri: http://${PRODUCT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/products
            - Method=GET
          filters:
            - SetPath=/api/product
        - id: product-service-all
          uri: http://${PRODUCT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/products/all
            - Method=GET
          filters:
            - SetPath=/api/product/all
        - id: order-service
          uri: http://${ORDER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/orders
            - Method=POST
          filters:
            - SetPath=/api/order
        - id: order-service-all
          uri: http://${ORDER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/orders
            - Method=GET
          filters:
            - SetPath=/api/order